import tkinter as tk
import tkinter.messagebox
window = tk.Tk()
window.title('Calculator')
frame = tk.Frame(window, padx=2 , pady=1)
frame.pack()
entry = tk.Entry(frame, width=40) 
entry.grid(row=0, column=0, columnspan=4,ipadx=35 , ipady=60, pady=2)
def myclick(number):
    number
def equal():
    equal = entry.get()
button_1 = tk.Button(frame, text='7', padx=35, pady=26, command=myclick(7))
button_1.grid(row=1, column=0, pady=2)
button_2 = tk.Button(frame, text='8', padx=35, pady=26, command=myclick(8))
button_2.grid(row=1, column=1, pady=2)
button_3 = tk.Button(frame, text='9',padx=35, pady=26, command=myclick(9))
button_3.grid(row=1, column=2, pady=2)
button_4 = tk.Button(frame, text='×', padx=35, pady=26, command=myclick(4))
button_4.grid(row=1, column=3, pady=2)
button_5 = tk.Button(frame, text='6', padx=35, pady=26, command=myclick(5))
button_5.grid(row=2, column=0, pady=2)
button_6 = tk.Button(frame, text='5', padx=35, pady=26, command=myclick(6))
button_6.grid(row=2, column=1, pady=2)
button_7 = tk.Button(frame, text='4',padx=35, pady=26, command=myclick(1))
button_7.grid(row=2, column=2, pady=2)
button_8 = tk.Button(frame, text='÷', padx=35, pady=26, command=myclick(2))
button_8.grid(row=2, column=3, pady=2)
button_9 = tk.Button(frame, text='3', padx=35, pady=26, command=myclick(3))
button_9.grid(row=3, column=0, pady=2)
button_10 = tk.Button(frame, text='2', padx=35, pady=26, command=myclick(3))
button_10.grid(row=3, column=1, pady=2)
button_11 = tk.Button(frame, text='1', padx=35, pady=26, command=myclick(3))
button_11.grid(row=3, column=2, pady=2)
button_12 = tk.Button(frame, text='+', padx=35, pady=26, command=myclick(3))
button_12.grid(row=3, column=3, pady=2)
button_0 = tk.Button(frame, text='+', padx=35, pady=26, command=myclick(0))
button_0.grid(row=4, column=0, pady=2)
button_01 = tk.Button(frame, text='0', padx=35, pady=26, command=myclick(0))
button_01.grid(row=4, column=1, pady=2)
button_02 = tk.Button(frame, text='.',padx=35, pady=26, command=myclick(0))
button_02.grid(row=4, column=2, pady=2)
button_03 = tk.Button(frame, text='=', bg="skyblue",padx=35, pady=26, command=myclick(0))
button_03.grid(row=4, column=3, pady=2)
window.mainloop()
